name: Bun CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Github checkout
        uses: actions/checkout@v2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v0.1.8
        with:
          bun-version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Server/Client
        strategy:
          matrix:
            directory: [./server, ./client]
        defaults:
          run:
            working-directory: ${{ matrix.directory }}
        steps:
          - name: Install dependencies
            run: bun install

          - name: Run tests
            run: bun run test
