name: Bun CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Github checkout
        uses: actions/checkout@v2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v0.1.8
        with:
          bun-version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}

  server:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Github checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun run test

  client:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Github checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun run test
